import React from 'react';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { Button } from 'react-native-paper';
import { useAuthStore } from '../store/authStore';
import { useLanguage } from '../i18n';
import { LoginScreen, RegisterScreen, ForgotPasswordScreen } from '../screens/AuthScreens';
import { EmployeeDashboard, PasswordChangeScreen, ProfileScreen, TimeEntryForm, TimeEntryList } from '../screens/EmployeeScreens';
import { AdminApprovals, AdminDashboard, CompanySettings, ComplianceAlerts, PositionsAdmin, Reports, UsersAdmin, WorkRules } from '../screens/AdminScreens';
const Stack = createNativeStackNavigator();
function HeaderLogout() { const logout=useAuthStore(s=>s.logout); const { tr } = useLanguage(); return <Button onPress={logout}>{tr('Log out','Logg ut')}</Button>; }
export function RootNavigator() { const user=useAuthStore(s=>s.user); const { tr } = useLanguage(); if(!user) return <Stack.Navigator><Stack.Screen name="Login" component={LoginScreen} options={{title:'TimeTrack'}}/><Stack.Screen name="Register" component={RegisterScreen} options={{title:tr('Register company','Registrer bedrift')}}/><Stack.Screen name="ForgotPassword" component={ForgotPasswordScreen} options={{title:tr('Forgot password','Glemt passord')}}/></Stack.Navigator>;
  const admin=user.role==='ADMIN'; return <Stack.Navigator screenOptions={{headerRight:()=> <HeaderLogout />}}>
    {admin ? <><Stack.Screen name="Admin" component={AdminDashboard}/><Stack.Screen name="Employees" component={UsersAdmin} options={{title:tr('Employees','Ansatte')}}/><Stack.Screen name="Positions" component={PositionsAdmin} options={{title:tr('Work roles','Arbeidsroller')}}/><Stack.Screen name="Company" component={CompanySettings} options={{title:tr('Company','Bedrift')}}/><Stack.Screen name="WorkRules" component={WorkRules} options={{title:tr('Work rules','Arbeidsregler')}}/><Stack.Screen name="Approvals" component={AdminApprovals} options={{title:tr('Approvals','Godkjenning')}}/><Stack.Screen name="Reports" component={Reports} options={{title:tr('Reports','Rapporter')}}/><Stack.Screen name="Alerts" component={ComplianceAlerts} options={{title:tr('Compliance alerts','Compliance-varsler')}}/><Stack.Screen name="TimeList" component={TimeEntryList} options={{title:tr('Timesheet','Timeliste')}}/><Stack.Screen name="NyTime" component={TimeEntryForm} options={{title:tr('Register hours','Registrer timer')}}/><Stack.Screen name="Profile" component={ProfileScreen} options={{title:tr('My details','Mine opplysninger')}}/><Stack.Screen name="ChangePassword" component={PasswordChangeScreen} options={{title:tr('Change password','Bytt passord')}}/></> : <><Stack.Screen name="Overview" component={EmployeeDashboard} options={{title:tr('Overview','Oversikt')}}/><Stack.Screen name="TimeList" component={TimeEntryList} options={{title:tr('Timesheet','Timeliste')}}/><Stack.Screen name="NyTime" component={TimeEntryForm} options={{title:tr('Register hours','Registrer timer')}}/><Stack.Screen name="Profile" component={ProfileScreen} options={{title:tr('My details','Mine opplysninger')}}/><Stack.Screen name="ChangePassword" component={PasswordChangeScreen} options={{title:tr('Change password','Bytt passord')}}/></>}
  </Stack.Navigator>; }
