import React, { useState } from 'react';
import { Button, TextInput, Text } from 'react-native-paper';
import { Layout } from '../components/Layout';
import { authApi } from '../api/client';
import { useAuthStore } from '../store/authStore';
import { useLanguage } from '../i18n';
export function LoginScreen({ navigation }: any) { const { tr } = useLanguage(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const setAuth=useAuthStore(s=>s.setAuth); return <Layout title={tr('Log in','Logg inn')}><TextInput label={tr('Email','E-post')} value={email} onChangeText={setEmail} autoCapitalize="none"/><TextInput label={tr('Password','Passord')} value={password} onChangeText={setPassword} secureTextEntry/>{error?<Text style={{color:'red'}}>{error}</Text>:null}<Button mode="contained" onPress={async()=>{try{setAuth(await authApi.login(email,password));}catch(e:any){setError(e.message)}}}>{tr('Log in','Logg inn')}</Button><Button onPress={()=>navigation.navigate('Register')}>{tr('Register company','Registrer bedrift')}</Button><Button onPress={()=>navigation.navigate('ForgotPassword')}>{tr('Forgot password?','Glemt passord?')}</Button></Layout> }
export function RegisterScreen() { const { tr } = useLanguage(); const [body,setBody]=useState<any>({ companyName:'', firstName:'', lastName:'', email:'', password:'' }); const [msg,setMsg]=useState(''); const setAuth=useAuthStore(s=>s.setAuth); const f=(k:string,v:string)=>setBody((b:any)=>({...b,[k]:v})); return <Layout title={tr('Register company and admin','Registrer bedrift og admin')}><TextInput label={tr('Company name','Bedriftsnavn')} value={body.companyName} onChangeText={v=>f('companyName',v)}/><TextInput label={tr('Organization number','Org.nr')} value={body.orgNumber} onChangeText={v=>f('orgNumber',v)}/><TextInput label={tr('Address','Adresse')} value={body.address} onChangeText={v=>f('address',v)}/><TextInput label={tr('First name','Fornavn')} value={body.firstName} onChangeText={v=>f('firstName',v)}/><TextInput label={tr('Last name','Etternavn')} value={body.lastName} onChangeText={v=>f('lastName',v)}/><TextInput label={tr('Email','E-post')} value={body.email} onChangeText={v=>f('email',v)} autoCapitalize="none"/><TextInput label={tr('Password','Passord')} value={body.password} onChangeText={v=>f('password',v)} secureTextEntry/><Text>{msg}</Text><Button mode="contained" onPress={async()=>{try{setAuth(await authApi.register({ ...body, email: body.email.trim() }));}catch(e:any){setMsg(e.message)}}}>{tr('Create account','Opprett konto')}</Button></Layout> }
export function ForgotPasswordScreen() { const { tr } = useLanguage(); const [email,setEmail]=useState(''); const [msg,setMsg]=useState(''); return <Layout title={tr('Forgot password','Glemt passord')}><TextInput label={tr('Email','E-post')} value={email} onChangeText={setEmail}/><Text>{msg}</Text><Button mode="contained" onPress={async()=>{const r=await authApi.forgot(email); setMsg(r.message)}}>{tr('Send link','Send lenke')}</Button></Layout> }
